"""
This is an example that runs starts an experiment from the CCLight.
For the CCL basics see CCL_example.py
"""
import pycqed as pq
import os

from pycqed.instrument_drivers.physical_instruments.QuTech_CCL import CCL
from pycqed.measurement.openql_experiments import single_qubit_oql as sqo

ccl = CCL('CCL', address='192.168.42.11', port=5025)

config_fn = os.path.join(pq.__path__[0], 'tests', 'test_cfg_CCL.json')
# Running this program generates 3 files.
#   .qisa    <-- the instructions
#   .dbpd    <-- the map file (used to build the assembler)
#   cs.txt   <-- the controlstore
p = sqo.AllXY(0, config_fn)


# This controlstore was generated by OpenQL and moved to
# this location beforehand.
ccl.upload_microcode('./qisa_test_assembly/cs.txt')

# The assembler needs to be rebuild whenver the config file
# for OpenQL changes.

ccl.eqasm_program(p.filename)
ccl.enable(1)
ccl.run(1)
