"""
Usage:
pytest -v pycqed/tests/openql/test_cqasm.py
pytest -v pycqed/tests/openql/test_cqasm.py --log-level=DEBUG --capture=no
"""

import unittest
import pathlib

#from utils import file_compare

import pycqed.measurement.openql_experiments.generate_CC_cfg_modular as gen
import pycqed.measurement.openql_experiments.cqasm.special_cq as spcq
import pycqed.measurement.openql_experiments.openql_helpers as oqh
from pycqed.measurement.openql_experiments.openql_helpers import OqlProgram


this_path = pathlib.Path(__file__).parent
output_path = pathlib.Path(this_path) / 'test_output_cc'
platf_cfg_path = output_path / 'config_cc_s17_direct_iq_openql_0_10.json'


class Test_cQASM(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        gen.generate_config_modular(platf_cfg_path)
        OqlProgram.output_dir = str(output_path)

    if oqh.is_compatible_openql_version_cc():  # we require unreleased version not yet available for CI
        def test_nested_rus_angle_0(self):
            ancilla1_idx = 10
            ancilla2_idx = 8
            data_idx = 11
            angle = 0

            p = spcq.nested_rus(
                str(platf_cfg_path),
                ancilla1_idx,
                ancilla2_idx,
                data_idx,
                angle
            )

            # check that a file with the expected name has been generated
            assert pathlib.Path(p.filename).is_file()

        @unittest.skip('CC backend cannot yet handle decomposition into if statements')
        def test_parameterized_gate_decomposition(self):
            name = f'test_parametrized_gate_decomp'
            src = f"""
                # Note:         file generated by {__file__}::test_parameterized_gate_decomposition
                # File:         {name}.cq
                # Purpose:      test parameterized gate decomposition

                version 1.2

                pragma @ql.name("{name}")  # set the name of generated files

                _test_rotate q[0],3                
            """

            p = OqlProgram(name, str(platf_cfg_path))  # NB: name must be identical to name set by "pragma @ql.name" above
            p.compile_cqasm(src)

        def test_hierarchical_gate_decomposition(self):
            name = f'test_hierarchical_gate_decomp'
            src = f"""
                # Note:         file generated by {__file__}::test_hierarchical_gate_decomposition
                # File:         {name}.cq
                # Purpose:      test hierarchical gate decomposition

                version 1.2

                pragma @ql.name("{name}")  # set the name of generated files

                _fluxdance_1                
            """

            p = OqlProgram(name, str(platf_cfg_path))  # NB: name must be identical to name set by "pragma @ql.name" above
            p.compile_cqasm(src)



    else:
        @unittest.skip('OpenQL version does not support CC')
        def test_fail(self):
            pass
